name: turbopy_atmospheric
channels:
        - defaults
dependencies: 
        - python=3.7
        - colorama
        - pip
        - pip:
                - pyshtools
                - pyatmos
                - turbopy
